import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect, useState } from "react";
import Form from "./components/Form";
import ImageContainer from "./components/ImageContainer";

const Join = () => {
  const [windowSize, setWindowSize] = useState({
    height: undefined,
  });

  useEffect(() => {
    function handleResize() {
      setWindowSize({
        height: window.scrollY,
      });
    }

    window.addEventListener("scroll", handleResize);

    handleResize();

    return () => window.removeEventListener("scroll", handleResize);
  }, []);

  const router = useRouter();

  return (
    <div>
      <Head>
        <title>PHOTONSNAP- Get An Invite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`w-full ${
          windowSize.height >= 200 ? "mt-[70px]" : "mt-0"
        } relative`}
      >
        <div className="absolute right-10 top-10">
          <p
            className="uppercase font-medium cursor-pointer hover:scale-110 duration-200"
            onClick={() => router.push("/")}
          >
            Go Back
          </p>
        </div>

        <div className="w-full min-h-screen flex justify-center items-center">
          <div className="w-[50%] hidden lg:block h-screen">
            <ImageContainer />
          </div>
          <div className="lg:w-[50%] w-full h-full flex justify-center items-center">
            <Form />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Join;
