import Head from "next/head";
import Header from "../components/Header/Header";

const Home = () => {
  return (
    <div>
      <Head>
        <title>PHOTONSNAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h1 className="text-blue-400">lasjjdfl</h1>
      </main>
    </div>
  );
};

export default Home;
